### ISSUE TITLE
[crystal spec] Error: for empty hashes use '{} of KeyType => ValueType'

### ISSUE THREAD

**Issue by grokify** [grokify/crystal-financialmodelingprep#2]
Error running `crystal spec`:

```bash
% crystal spec
In src/financialmodelingprep/configuration.cr:220:11

 220 | Hash{
           ^
Error: for empty hashes use '{} of KeyType => ValueType'
```

The code is:

```crystal
    def auth_settings
      Hash{
      }
    end
```

This API takes the access token as a query string parameter so a formal auth setting may not be needed.

**Comment by grokify** [comment]
Workaround added in: 656d3797f2883c80d3efa071c688b5539b39e4c2

**Comment by grokify** [comment]
Closing due to manual workaround but a more permanent solution is needed.

Workaround tag is left to make this trackable.

**Comment by cyangle** [comment]
@grokify The generator supports apikey auth in query.

You need to define it in `securitySchemes` under `components` in your OpenAPI specification file.

Check https://github.com/cyangle/pet_store/blob/3d2328018b17b7e83d6441a754550c93eb1c1ac3/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1218 for an example definition of api key in query.

And then you need to reference it in the `security` section of `path` like here: https://github.com/cyangle/pet_store/blob/3d2328018b17b7e83d6441a754550c93eb1c1ac3/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L584

**Comment by grokify** [comment]
Thanks @cyangle! OAS security for API key has been added in v0.2.0.
